### ISSUE TITLE
Simpler mkdir

### ISSUE THREAD

**Issue by aldnav** [vernere98/exercises#1]
https://github.com/vernere98/exercises/blob/7513a06809c4e87fc4d90c7ac91d3ceacb55c98e/00_trash.sh#L25

This can just be `mkdir -p ~/.mytrash/`. See `mkdir --help`.
Also fix the indentation.

https://github.com/vernere98/exercises/blob/master/00_trash.sh#L23-L28
```sh
	for var in $@; 
	do
			[ ! -d ~/.mytrash/ ] && mkdir ~/.mytrash/
	        mv "$var" ~/.mytrash/
    echo "Trashing files"
done
```

Other than that, lgtm :+1:

**Comment by vernere98** [comment]
Okay, thanks for the advice.
